train:
  _target_: src.datasets.LibrispeechDataset
  split: "test-clean"
  instance_transforms: ${transforms.instance_transforms.train}
  target_sample_rate: ${consts.sample_rate}
  limit: ${dataloader.batch_size}
  dataset_dir: null
  save_index: True

validation:
  _target_: src.datasets.LibrispeechDataset
  split: "test-clean"
  instance_transforms: ${transforms.instance_transforms.inference}
  target_sample_rate: ${consts.sample_rate}
  limit: ${dataloader.batch_size}
  dataset_dir: null
  save_index: True
