_target_: src.models.generator.SoundStream
encoder:
  _target_: src.models.generator.Encoder
  out_channels: 2
  hidden_channels: 4
  strides: [2, 4, 5, 5]

rvq:
  _target_: src.models.generator.RVQ

decoder:
  _target_: src.models.generator.Decoder
  in_channels: 2
  hidden_channels: 4
  strides: [2, 4, 5, 5]
