_target_: src.models.generator.SoundStream
encoder:
  _target_: src.models.generator.Encoder
  out_channels: 128
  hidden_channels: 32
  strides: [2, 4, 5, 5]

rvq:
  _target_: src.models.generator.RVQ
  n_quantizers: 10
  embedding_dim: 128
  codebook_size: 256
  decay: 0.99
  min_stat: 2

decoder:
  _target_: src.models.generator.Decoder
  in_channels: 128
  hidden_channels: 32
  strides: [5, 5, 4, 2]

target_sample_rate: ${consts.sample_rate}
