defaults:
  - generator/model: soundstream
  - writer: cometml
  - metrics: audio
  - datasets: librispeech_test
  - dataloader: simple
  - transforms: librispeech
  - _self_

model:
  _target_: src.models.generator.SoundStream.from_pretrained
  path: "best_model.pth" # path to the pretrained model

consts:
  device: "auto"
  sample_rate: 16000
  div_length: 200

inferencer:
  device_tensors: ["audio"]
  device: ${consts.device}
  save_dir: "saved"
  seed: 1
