defaults:
  - generator/model: soundstream
  - discriminator/model: soundstream
  - writer: cometml
  - metrics: audio
  - datasets: librispeech_train
  - dataloader: simple
  - transforms: librispeech
  - _self_

generator:
  optimizer:
    _target_: torch.optim.Adam
    lr: 1e-4
    betas: [0.5, 0.9]

  lr_scheduler:
    _target_: torch.optim.lr_scheduler.ConstantLR
    factor: 1.0
    total_iters: 0

  loss_function:
    _target_: src.loss.GeneratorLoss
    lambda_adversarial: 1
    lambda_feature: 100
    lambda_reconstruction: 1
    lambda_commitment: 1

discriminator:
  optimizer:
    _target_: torch.optim.Adam
    lr: 1e-4
    betas: [0.5, 0.9]

  lr_scheduler:
    _target_: torch.optim.lr_scheduler.ConstantLR
    factor: 1.0
    total_iters: 0

  loss_function:
    _target_: src.loss.DiscriminatorLoss

trainer:
  log_step: 50
  n_epochs: 100
  epoch_len: 500
  device_tensors: ["audio"]
  resume_from: null
  device: "auto"
  override: False
  monitor: "max STOI"
  save_period: 5
  early_stop: ${trainer.n_epochs}
  save_dir: "saved"
  seed: 1
